/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionForm = IDL.Record({
  'age' : IDL.Nat,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryItem = IDL.Record({
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'text' : IDL.Text,
  'photoKey' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllAdmissions' : IDL.Func([], [IDL.Vec(AdmissionForm)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryItem)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishGalleryItem' : IDL.Func([GalleryItem], [], []),
  'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'saveTestimonial' : IDL.Func([Testimonial], [], []),
  'submitAdmissionForm' : IDL.Func([AdmissionForm], [], []),
  'submitContactForm' : IDL.Func([ContactForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionForm = IDL.Record({
    'age' : IDL.Nat,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryItem = IDL.Record({
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'text' : IDL.Text,
    'photoKey' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllAdmissions' : IDL.Func([], [IDL.Vec(AdmissionForm)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryItem)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishGalleryItem' : IDL.Func([GalleryItem], [], []),
    'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'saveTestimonial' : IDL.Func([Testimonial], [], []),
    'submitAdmissionForm' : IDL.Func([AdmissionForm], [], []),
    'submitContactForm' : IDL.Func([ContactForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };