/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionForm {
  'age' : bigint,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'childName' : string,
  'parentName' : string,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'title' : string,
  'blob' : ExternalBlob,
  'timestamp' : bigint,
  'category' : string,
}
export interface Testimonial {
  'text' : string,
  'photoKey' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'rating' : bigint,
  'parentName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllAdmissions' : ActorMethod<[], Array<AdmissionForm>>,
  'getAllContacts' : ActorMethod<[], Array<ContactForm>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryItemsByCategory' : ActorMethod<[string], Array<GalleryItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'removeGalleryItem' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveTestimonial' : ActorMethod<[Testimonial], undefined>,
  'submitAdmissionForm' : ActorMethod<[AdmissionForm], undefined>,
  'submitContactForm' : ActorMethod<[ContactForm], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];